name: IMPA
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - cudatoolkit=11.3.1
  - pytorch::pytorch=1.8.0
  - pytorch::torchvision=0.9.0
  - pytorch::torchaudio=0.8.0
  - tensorboard==2.8.0
  - psutil
  - pandas
  - notebook=6.4.8
  - rdkit=2021.09.2
  - pip:
    - matplotlib==3.5.2
    - munch==2.5.0
    - pillow==9.1.1
    - pymongo==4.0.2
    - sacred==0.8.2
    - scikit-image==0.19.1
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - seml==0.3.6
    - tqdm==4.62.3
    - git+https://github.com/bp-kelley/descriptastoru
    