name: IMPA
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip 
  - pip:
    - torch==2.1.0
    - torchvision==0.16.0
    - torchvision 
    - pytorch-lightning==2.1.0
    - pandas
    - numpy
    - scipy
    - matplotlib==3.5.2
    - munch==2.5.0
    - pillow==9.1.1
    - sacred==0.8.2
    - scikit-image==0.19.1
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - tqdm==4.62.3
    - imageio==2.35.1
    - jupyterlab
    - munch==2.5.0
    - tqdm==4.62.3
    - wandb==0.15.12
    - umap-learn==0.5.6
    - transformers==4.26.1
    - seaborn==0.11.2
    - rdkit==2023.9.5
    - POT==0.9.1
    - hydra-core==1.3.2
    - hydra-optuna-sweeper==1.2.0
    - hydra-submitit-launcher==1.2.0
