# TASK NAME 
task_name: bbbc021_six

# NETWORK
img_size: 96  
latent_dim: 1024  # The dimension of the Morgan fingerprints (matters for trainable embeddings)
hidden_dim: 512 
style_dim: 64  # Dimension of the style space
stochastic: True 
z_dimension: 16  
dim_in: 64 

# LOSS 
lambda_reg: 1 
lambda_cyc: 1 
lambda_sty: 1 
lambda_ds: 1 

# TRAINING 
total_epochs: 2
ds_iter: 100000  # Number of iterations over which the diversity loss weight is decreased
resume_iter: 0  # Iteration for resuming training
batch_size: 32
val_batch_size: 20
lr: 0.0001  # Model learning rate
f_lr: 0.0001  # Perturbation encoder's learning rate
beta1: 0
beta2: 0.99
weight_decay: 0.0001
num_outs_per_domain: 10
single_style: True # If true, shared encoding space per condition
ood_set: Null  # Set of held-out molecules 
mol_list: ['AZ138', 'AZ258', 'cytochalasin B', 'DMSO', 'taxol', 'vincristine']  # Subset of molecules to train on 
trainable_emb: False
dataset_name: 'bbbc021'
n_channels: 3
num_workers: 6
seed: 42  
multimodal: False  # True if multiple perturbation modalities
batch_correction: False  # True if batch correction task 
batch_key: Null
use_condition_embeddings: False
add_controls: False  # True if controls are added to the perturbation prediction task (mapping controls to self)
condition_embedding_dimension: null
n_mod: 1
modality_list: 
  - Compound

# DIRECTORIES FOR DATA
image_path: project_folder/datasets/bbbc021_six
data_index_path: project_folder/datasets/bbbc021_six/metadata/bbbc021_df_six.csv
embedding_path: embeddings/csv/emb_fp.csv

# DIRECTORIES FOR RESULTS 
experiment_directory: project_folder/experiments/
sample_dir: sample   # Name of directory for sampled images 
checkpoint_dir: checkpoint  # Name of directory for checkpoints
naming_key: dataset_name
resume_dir: ''

# DATA HANDLING 
augment_train: True 
normalize: True

# LOGGING INFO 
print_every: 10
sample_every: 1000
save_every: 500
eval_every: 500

# PARAMETERS FOR CONDITION ENCODING 
encode_rdkit: True  # True if a perturbation encoder is used to down project the condition embedding
num_layers_mapping_net: 1

# Lightning 
filename: epoch_{epoch:04d}
monitor: fid_transformations
mode: min
save_last: True
offline: False
project: bbbc021_six
log_model: False
accelerator: gpu 
log_every_n_steps: 10
