# TASK NAME 
task_name: cpg0000_batch

# NETWORK
img_size: 96  
latent_dim: 100  # The dimension of the Morgan fingerprints
hidden_dim: 512 
style_dim: 64 
stochastic: True 
z_dimension: 10  
dim_in: 64 

# LOSS 
lambda_reg: 1 
lambda_cyc: 1 
lambda_sty: 1 
lambda_ds: 1 

# TRAINING 
total_epochs: 150
ds_iter: 200000
resume_iter: 0
batch_size: 32
val_batch_size: 20
lr: 0.0001
f_lr: 0.0001
beta1: 0
beta2: 0.99
weight_decay: 0.0001
num_outs_per_domain: 10
single_style: True
ood_set: null
mol_list: null
balanced: False
trainable_emb: True
dataset_name: 'cpg0000'
n_channels: 5
num_workers: 6
seed: 42  
multimodal: False
batch_correction: True
batch_key: PLATE
use_condition_embeddings: False
add_controls: False
condition_embedding_dimension: null
modality_list: 
  - Compound

# DIRECTORIES FOR DATA
image_path: project_folder/datasets/cpg0000/cpg0000_u2os_normalized_segmented_large
data_index_path: project_folder/datasets/cpg0000/metadata/metadata_large.csv
embedding_path:
  Compound: embeddings/cpg0000/cpd_embeddings.csv
  CRISPR: embeddings/cpg0000/crispr_embeddings.csv
  ORF: embeddings/cpg0000/orf_embeddings.csv

# DIRECTORIES FOR RESULTS  
experiment_directory: project_folder/experiments/
sample_dir: sample   # Name of directory for sampled images 
checkpoint_dir: checkpoint  # Name of directory for checkpoints
basal_vs_real_folder: basal_vs_real
naming_key: dataset_name
embedding_folder: embeddings 
resume_dir: ''

# DATA HANDLEMENT 
augment_train: True 
normalize: True

# LOGGING INFO 
print_every: 10
sample_every: 1000
save_every: 500
eval_every: 500

# PARAMETERS FOR CONDITION ENCODING 
encode_rdkit: True
num_layers_mapping_net: 1

# Lightning 
filename: epoch_{epoch:04d}
monitor: fid_transformations
mode: min
save_last: True
offline: False
project: cpg0000
log_model: False
accelerator: gpu 
log_every_n_steps: 10
