task_name: cpg0000_multimodal_condition_emb
img_size: 96
latent_dim: 100
hidden_dim: 512
style_dim: 32
stochastic: true
z_dimension: 20
dim_in: 64
lambda_reg: 1
lambda_cyc: 1
lambda_sty: 1
lambda_ds: 1
total_epochs: 100
ds_iter: 200000
resume_iter: 0
batch_size: 32
val_batch_size: 20
lr: 0.0001
f_lr: 0.0001
beta1: 0
beta2: 0.99
weight_decay: 0.0001
num_outs_per_domain: 10
single_style: true
ood_set: null
mol_list: null
balanced: false
trainable_emb: false
dataset_name: cpg0000
n_channels: 5
num_workers: 6
seed: 42
image_path: /lustre/groups/ml01/datasets/projects/cpg0000_alessandro/cpg0000_u2os_normalized_segmented_large_transported
data_index_path: /lustre/groups/ml01/datasets/projects/cpg0000_alessandro/metadata/metadata_large_gene2vec.csv
experiment_directory: ../project_folder/experiments
sample_dir: sample
checkpoint_dir: checkpoint
basal_vs_real_folder: basal_vs_real
naming_key: dataset_name
embedding_folder: embeddings
resume_dir: ''
augment_train: true
normalize: true
print_every: 10
sample_every: 1000
save_every: 500
eval_every: 500
encode_rdkit: true
num_layers_mapping_net: 1
filename: epoch_{epoch:04d}
monitor: fid_transformations
mode: min
save_last: true
offline: false
project: cpg0000_multimodal_condition_emb
log_model: true
accelerator: gpu
log_every_n_steps: 10
add_controls: false
embedding_path:
  Compound: /home/icb/alessandro.palma/environment/IMPA/IMPA/embeddings/cpg0000/cpd_embeddings.csv
  CRISPR: /home/icb/alessandro.palma/environment/IMPA/IMPA/embeddings/cpg0000/crispr_embeddings.csv
  ORF: /home/icb/alessandro.palma/environment/IMPA/IMPA/embeddings/cpg0000/orf_embeddings.csv
multimodal: true
modality_list:
  - CRISPR
  - Compound
  - ORF
use_condition_embedding: True
condition_embedding_dimension: 10
