seml:
  executable: /home/icb/alessandro.palma/IMPA/imCPA/compert/main.py
  name: bbbc021_all_drugs
  output_dir: path-to-output-dir
  conda_environment: IMPA
  project_root_dir: /home/icb/alessandro.palma/IMPA/imCPA/

slurm:
  max_simultaneous_jobs: 10
  experiments_per_job: 1
  sbatch_options_template: GPU
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 90G          # memory
    cpus-per-task: 6  # num cores
    time: 2-00:00     # max time, D-HH:MM

########## HUPERPARAMETER TUNING ##########

fixed: 
  # General parameters
  train.args.img_size: 96
  train.args.latent_dim: 160
  train.args.hidden_dim: 512
  train.args.style_dim: 64
  train.args.stochastic: True
  train.args.z_dimension: 64
  train.args.dim_in: 64

  # weight for objective functions
  train.args.lambda_reg: 1
  train.args.lambda_cyc: 1
  train.args.lambda_sty: 1
  train.args.lambda_ds: 1

  # training arguments
  train.args.total_iters: 100000
  train.args.ds_iter: 100000  
  train.args.resume_iter: 0
  train.args.batch_size: 32
  train.args.val_batch_size: 20
  train.args.lr: 0.0001
  train.args.f_lr: 0.0001
  train.args.beta1: 0
  train.args.beta2: 0.99
  train.args.weight_decay: 0.0001
  train.args.num_outs_per_domain: 10
  train.args.single_style: True
  train.args.ood_set: [docetaxel, AZ841, cytochalasin D, simvastatin, cyclohexamide, latrunculin B, epothilone B, lactacystin]
  train.args.mol_list: Null
  train.args.balanced: True
  train.args.trainable_emb: False
  train.args.dataset_name: 'bbbc021'
  train.args.n_channels: 3

  # misc
  train.args.mode: train
  train.args.num_workers: 6
  train.args.seed: 42  
    
  # directory for training
  train.args.image_path: path-to-output-images
  train.args.data_index_path: path-to-output-data-index
  train.args.embedding_path: path-to-output-embeddings 

  # Directories for results
  train.args.experiment_directory: path-to-output-experiments
  train.args.sample_dir: sample   # Name of directory for sampled images 
  train.args.checkpoint_dir: checkpoint  # Name of directory for checkpoints
  train.args.basal_vs_real_folder: basal_vs_real
  train.args.naming_key: dataset_name
  train.args.embedding_folder: embeddings 
  train.args.resume_dir: ''

  # face alignment
  train.args.augment_train: True 
  train.args.normalize: True

  # step size
  train.args.print_every: 10
  train.args.sample_every: 1000
  train.args.save_every: 500
  train.args.eval_every: 500

  # Neural network parameters
  train.args.encode_rdkit: True
  train.args.num_layers_mapping_net: 1
