args: 
  # General parameters
  img_size: 96
  latent_dim: 200
  hidden_dim: 512
  style_dim: 64
  stochastic: True
  z_dimension: 16
  dim_in: 64

  # weight for objective functions
  lambda_reg: 1
  lambda_cyc: 1
  lambda_sty: 1
  lambda_ds: 1

  # training arguments
  total_iters: 100000
  ds_iter: 100000  
  resume_iter: 0
  batch_size: 32
  val_batch_size: 3
  lr: 0.0001
  f_lr: 0.0001
  beta1: 0
  beta2: 0.99
  weight_decay: 0.0001
  num_outs_per_domain: 10
  single_style: True
  ood_set: []
  mol_list: Null
  balanced: True
  trainable_emb: True
  dataset_name: 'recursion'
  n_channels: 6

  # misc
  mode: train
  num_workers: 6
  seed: 42  
    
  # directory for training
  image_path: ../project_folder/datasets/rxrx1
  data_index_path: ../project_folder/datasets/rxrx1/metadata/rxrx1_df.csv
  embedding_path: ../embeddings/csv/rxrx1_gene2vec_embeddings.csv

  # Directories for results
  experiment_directory: ../project_folder/experiments/
  sample_dir: sample   # Name of directory for sampled images 
  checkpoint_dir: checkpoint  # Name of directory for checkpoints
  basal_vs_real_folder: basal_vs_real
  naming_key: dataset_name
  embedding_folder: embeddings 
  resume_dir: ''

  # face alignment
  augment_train: True 
  normalize: True

  # step size
  print_every: 10
  sample_every: 1000
  save_every: 500
  eval_every: 500

  # Neural network parameters
  encode_rdkit: True
  num_layers_mapping_net: 1
      