# TASK NAME 
task_name: rxrx1_batch

# IMAGE
img_size: 96  
latent_dim: 100 
hidden_dim: 512 
style_dim: 64 
stochastic: True 
z_dimension: 10 
dim_in: 64 
add_controls: False


# LOSS
lambda_reg: 1 
lambda_cyc: 1 
lambda_sty: 1 
lambda_ds: 1 

# TRAINING 
total_epochs: 200
ds_iter: 100000  
resume_iter: 0
batch_size: 32
val_batch_size: 20
lr: 0.0001
f_lr: 0.0001
beta1: 0
beta2: 0.99
weight_decay: 0.0001
num_outs_per_domain: 10
single_style: True
ood_set: Null
mol_list: Null
balanced: False 
trainable_emb: True
dataset_name: rxrx1
n_channels: 6
num_workers: 6
seed: 42  

# DIRECTORIES FOR DATA
image_path: /home/icb/alessandro.palma/environment/IMPA/IMPA/project_folder/datasets/rxrx1
data_index_path: /home/icb/alessandro.palma/environment/IMPA/IMPA/project_folder/datasets/rxrx1/metadata/rxrx1_df_full.csv
embedding_path: Null

# DIRECTORIES FOR RESULTS 
experiment_directory: /home/icb/alessandro.palma/environment/IMPA/IMPA/project_folder/experiments/
sample_dir: sample   # Name of directory for sampled images 
checkpoint_dir: checkpoint  # Name of directory for checkpoints
basal_vs_real_folder: basal_vs_real
naming_key: dataset_name
embedding_folder: embeddings 
resume_dir: ''

# DATA HANDLEMENT 
augment_train: True 
normalize: True

# LOGGING INFO 
print_every: 10
sample_every: 1000
save_every: 500
eval_every: 500

# PARAMETERS FOR CONDITION ENCODING 
encode_rdkit: True
num_layers_mapping_net: 1

# Lightning 
filename: epoch_{epoch:04d}
monitor: fid_transformations
mode: min
save_last: True
offline: False
project: rxrx1_batch
log_model: False
accelerator: gpu 
log_every_n_steps: 10 